Jira:
  # Jira 地址
  url: 'http://jira.oa.ikasinfo.com/'
  # 用户名
  username: 'yu.xin'
  # 密码
  password: 'ikas2022!'
  # 工时
  tempo:
    # issue 关键字
    issue_key: 'IAIMPCPH-55'
    # 开始日期
    start_date: '2022-11-05'
    # 结束日期
    end_date: '2022-11-30'
